### ISSUE TITLE
'focus' event not firing for controller elements

### ISSUE THREAD

**Issue by rubbingalcoholic** [lyonbros/composer.js#31]
This event doesn't work in my controller:

    events: {
        'focus textarea': 'focusTextareaFn',
    },

This works, but does not produce the intended effect:

    events: {
        'click textarea': 'focusTextareaFn',
    },

Also, when I specify the event manually in the render function, it works:

    textarea.onfocus = this.focusTextareaFn.bind(this);

Note the textarea is appended to a container and into `this.el` via the `this.html` function.

**Comment by orthecreedence** [comment]
This explains it pretty well: http://www.quirksmode.org/blog/archives/2008/04/delegating_the.html

Turns out that 'focus' and 'blur' events are one of the few in JS that don't bubble. So in order for them for work, "capturing" has to be enabled (`true` to the third arg of `addEventListener`).

One possible solution is to auto-capture events of a certain type (mootools does this with focus/blur when using addEvent).

**Comment by orthecreedence** [comment]
Ok, should be fixed: ed54d4c10843fdc22865ac765b9a2a6d3611fad0

**Comment by rubbingalcoholic** [comment]
Thanks!
